# Generated by Django 4.1.13 on 2024-01-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20231223_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='BroughtBy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='CareOfPerson',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Case',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='CityTaluka',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ConditionDuringArrival',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ContactNumber',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='MiddleName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ModeOfArrival',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ReferredBy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='RelationWithPatient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Religion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='State',
        ),
    ]
