# Generated by Django 4.1.13 on 2024-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_allergy_patient_blood_patient_card_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='Insurance_Provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='member_num',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relationship',
        ),
        migrations.AddField(
            model_name='patient',
            name='membernum',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='Insurance_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='Relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
